language: node_js

node_js:
  - "stable"

before_script:
  - npm install

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  api_token: "$NPM_TOKEN"
  cleanup: false
